# Use the official Nginx image
FROM nginx:alpine

# Copy built React app (dist or build) to Nginx html directory
COPY /src/dist/ /usr/share/nginx/html/

# Create a directory for SSL certificates
RUN mkdir -p /etc/nginx/credentials
# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose HTTPS port
EXPOSE 443
# Expose HTTP port
EXPOSE 80

# Start Nginx
CMD ["nginx"]