server {
    listen 443 ssl;
    listen 80;
    server_name codejam-frontend;

    ssl_certificate     /etc/nginx/credentials/cert.pem;
    ssl_certificate_key /etc/nginx/credentials/key.pem;

    root /usr/share/nginx/html; # Adjust if your dist is copied elsewhere

    location / {
        try_files $uri /index.html;
    }
}