# Use the Python 3.11 image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 5801

CMD ["python", "src/main.py"]
