# Use an official Node.js runtime as a parent image
FROM node:14

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Set the working directory to /app
WORKDIR /app

# Create a non-root user and switch to that user
RUN useradd -m user -d /app
USER user



